export const MOBILE_COPY = {
  APP_NAME: "Computer Room",
  LOADING: "연결하는 중…",
  LOAD_FAILED: "페이지를 불러오지 못했습니다.",
  RETRY: "다시 시도",
  BACK: "뒤로",
  HOME: "홈",
  MENU: "메뉴",
  CLOSE_MENU: "메뉴 닫기",
  MY_DOCUMENTS: "내 문서",
  MY_COMPUTER: "내 컴퓨터",
  RECYCLE_BIN: "휴지통",
  REFRESH: "새로 고침",
  DETAILS: "상세 정보",
  SORT: "정렬",
  SORT_TITLE: (name: string) => `${name} 정렬`,
  APPLY: "적용",
  LOGOUT: "로그아웃",
  HOME_SCREEN: "홈 화면",
  HOME_PAGES: "홈 화면 페이지",
  NAVIGATION_LABEL: "Android 탐색",
  CURRENT_PATH: "현재 경로",
  DIRECTORY_KIND: "폴더",
  WIDGET_KIND: "프로그램 문서",
  EMPTY_DIRECTORY: "이 폴더는 비어 있습니다.",
  EMPTY_TRASH: "휴지통이 비어 있습니다.",
  LOAD_MORE: "더 보기",
  DOWNLOAD: "다운로드",
  DOWNLOAD_CONFIRM: (name: string) => `${name} 파일을 다운로드할까요?`,
  CANCEL: "취소",
  CONFIRM: "확인",
  FILE_SIZE: "크기",
  ORIGINAL_LOCATION: "원래 위치",
  DELETED_AT: "삭제한 날짜",
  WIDGET_CATALOG_DESCRIPTION: "사용할 기능을 선택하세요.",
  CREATE_MEMO: "새 메모",
  CREATE_CHECKLIST: "새 일일 체크리스트",
  OPEN_STORAGE_STATUS: "저장소 상태",
  DRAFT_EXISTS_TITLE: "작성 중인 프로그램",
  DRAFT_EXISTS_MESSAGE:
    "먼저 작성 중인 프로그램을 이어서 쓰거나 삭제해 주세요.",
  RESUME_DRAFT: "이어쓰기",
  DELETE_DRAFT: "초안 삭제",
  DELETE_DRAFT_CONFIRM: "작성 중인 초안을 삭제할까요?",
  SAVE_LOCAL: "저장",
  SAVE_AS_FILE: "파일로 저장",
  LOCAL_SAVED: "이 기기에 저장했습니다.",
  DISCARD_CHANGES: "변경 취소",
  KEEP_EDITING: "계속 편집",
  UNSAVED_CHANGES: "저장하지 않은 변경 사항이 있습니다.",
  DRAFT_STORAGE_FAILED: "이 기기에 초안을 저장할 수 없습니다.",
  DRAFT_CORRUPTED: "손상된 로컬 초안을 삭제했습니다.",
  FILE_SAVE_TITLE: "프로그램 문서로 저장",
  FILE_NAME: "파일 이름",
  SAVE_LOCATION: "저장 위치",
  SAVE_HERE: "여기에 저장",
  SAVING: "저장 중…",
  SAVE_FAILED: "프로그램 문서를 저장하지 못했습니다.",
  NO_SUBDIRECTORIES: "하위 폴더가 없습니다.",
  EDIT: "편집",
  DONE: "완료",
  ADD_ITEM: "항목 추가",
  NEW_ITEM_PLACEHOLDER: "새 체크 항목",
  EDIT_ITEM: "수정",
  DELETE_ITEM: "삭제",
  HISTORY: "로그",
  NO_LOGS: "기록이 없습니다.",
  STATUS_DRAFT_RETAINED:
    "로그아웃해도 이 기기의 작성 중 초안은 유지됩니다.",
  WALLPAPER: "배경화면",
  WALLPAPER_PREVIEW: "배경화면 미리보기",
  DEFAULT_WALLPAPER: "기본 Android 배경",
  USE_DEFAULT_WALLPAPER: "기본 배경 사용",
  SET_WALLPAPER: "배경화면 설정",
  NO_WALLPAPER_IMAGES: "이 폴더에는 선택할 수 있는 이미지가 없습니다.",
  WALLPAPER_LOAD_FAILED: "배경화면 설정을 불러오지 못했습니다.",
  WALLPAPER_SAVE_FAILED: "배경화면 설정을 저장하지 못했습니다.",
  WALLPAPER_PREVIEW_FAILED: "이 이미지를 배경화면으로 표시할 수 없습니다.",
  SORT_SAVE_FAILED: "정렬 설정을 저장하지 못했습니다.",
} as const;
