export const GUEST_ACCESS_SETTINGS_SINGLETON_ID = 1;

export const GUEST_PUBLICATION_STATE = {
  PRIVATE: "private",
  PARTIAL: "partial",
  PUBLIC: "public",
} as const;

export const GUEST_PUBLICATION_STATE_VALUES = [
  GUEST_PUBLICATION_STATE.PRIVATE,
  GUEST_PUBLICATION_STATE.PARTIAL,
  GUEST_PUBLICATION_STATE.PUBLIC,
] as const;
