export const FILESYSTEM_UPLOAD_POLICY = {
  CONCURRENCY: 3,
} as const;

export const FILESYSTEM_DRAG_SOURCE = {
  ACTIVE: "active",
  TRASH: "trash",
} as const;

export const FILE_PICKER_ABORT_ERROR_NAME = "AbortError";

export const FILESYSTEM_SELECTION_DATA_ATTRIBUTE =
  "data-filesystem-selection-id";
export const FILESYSTEM_SELECTION_SELECTOR =
  `[${FILESYSTEM_SELECTION_DATA_ATTRIBUTE}]`;

export const FILESYSTEM_SELECTION_POLICY = {
  AUTO_SCROLL_EDGE_PX: 28,
  AUTO_SCROLL_STEP_PX: 18,
} as const;

export const EXPLORER_WINDOW_ID_PREFIX = "explorer-window-";

export const DESKTOP_ENTRY_UNORDERED_INDEX = Number.MAX_SAFE_INTEGER;

export const FILE_SIZE_DISPLAY = {
  KILOBYTE_BYTES: 1_000,
  MEGABYTE_BYTES: 1_000_000,
  GIGABYTE_BYTES: 1_000_000_000,
  TERABYTE_BYTES: 1_000_000_000_000,
  FRACTION_DIGITS: 1,
} as const;
