export const GUEST_COPY = {
  DESKTOP_TITLE: "공개된 개인 공간",
  MOBILE_TITLE: "공개 공간",
  PREPARING: "공개된 항목을 불러오는 중입니다.",
  DISABLED_TITLE: "게스트 접속이 닫혀 있습니다",
  DISABLED_DESCRIPTION:
    "현재는 공개된 공간을 볼 수 없습니다. 소유자는 로그인할 수 있습니다.",
  LOGIN: "로그인",
  GUEST_ACCOUNT: "게스트",
  START_MENU_DESCRIPTION: "공개된 파일과 프로그램 문서를 읽을 수 있습니다.",
  OPEN: "열기",
  DOWNLOAD: "다운로드",
  REFRESH: "새로 고침",
  CLOSE: "닫기",
  MY_DOCUMENTS: "내 문서",
  DESKTOP: "바탕 화면",
  PUBLIC_SPACE: "공개 공간",
  EMPTY_DIRECTORY: "공개된 항목이 없습니다.",
  LOAD_FAILED: "공개된 항목을 불러오지 못했습니다.",
  PROGRAM_LOAD_FAILED: "프로그램 문서를 불러오지 못했습니다.",
  UNSUPPORTED_FILE: "이 파일은 브라우저에서 바로 볼 수 없어 다운로드합니다.",
  ITEM_COUNT: (count: number) => `${count}개 항목`,
  CHECKLIST_DATE: (date: string) => `${date} 체크리스트`,
} as const;
