export const CHECKLIST_EVENT_ACTION = {
  ADDED: "added",
  RENAMED: "renamed",
  DELETED: "deleted",
  CHECKED: "checked",
  UNCHECKED: "unchecked",
} as const;

export const CHECKLIST_EVENT_ACTION_VALUES = [
  CHECKLIST_EVENT_ACTION.ADDED,
  CHECKLIST_EVENT_ACTION.RENAMED,
  CHECKLIST_EVENT_ACTION.DELETED,
  CHECKLIST_EVENT_ACTION.CHECKED,
  CHECKLIST_EVENT_ACTION.UNCHECKED,
] as const;

export const CHECKLIST_ITEM_LABEL_MAX_LENGTH = 200;
export const MAX_ACTIVE_CHECKLIST_ITEMS = 100;
