export const KEYBOARD_KEY = {
  ENTER: "Enter",
  ESCAPE: "Escape",
  HOME: "Home",
  END: "End",
  ARROW_LEFT: "ArrowLeft",
  ARROW_RIGHT: "ArrowRight",
  ARROW_UP: "ArrowUp",
  ARROW_DOWN: "ArrowDown",
  SPACE: " ",
  F10: "F10",
  CONTEXT_MENU: "ContextMenu",
  PLUS: "+",
  EQUAL: "=",
  MINUS: "-",
  ZERO: "0",
  A: "a",
} as const;
