import type { CSSProperties } from "react";
import { WIDGET_TYPE } from "@/constants/widgets/widget";

export const MOBILE_LAYOUT = {
  NAVIGATION_BAR_HEIGHT_PX: 52,
  ACTIVITY_HEADER_HEIGHT_PX: 48,
  HOME_ICON_CELL_WIDTH_PX: 86,
  HOME_ICON_CELL_HEIGHT_PX: 96,
  HOME_FALLBACK_COLUMNS: 4,
  HOME_FALLBACK_ROWS: 4,
  HOME_PAGE_GAP_PX: 12,
  MENU_Z_INDEX: 100,
  DIALOG_Z_INDEX: 200,
} as const;

export const MOBILE_LAYOUT_CSS_VARIABLES: CSSProperties &
  Record<`--${string}`, string> = {
  "--android-navigation-bar-height": `${MOBILE_LAYOUT.NAVIGATION_BAR_HEIGHT_PX}px`,
  "--android-activity-header-height": `${MOBILE_LAYOUT.ACTIVITY_HEADER_HEIGHT_PX}px`,
  "--android-menu-z-index": `${MOBILE_LAYOUT.MENU_Z_INDEX}`,
  "--android-dialog-z-index": `${MOBILE_LAYOUT.DIALOG_Z_INDEX}`,
};

export const MOBILE_CSS_VARIABLE = {
  HOME_WALLPAPER_IMAGE: "--android-home-wallpaper-image",
} as const;

export const MOBILE_ASSET_PATHS = {
  DOCUMENTS: "/assets/android/documents.svg",
  COMPUTER: "/assets/android/computer.svg",
  RECYCLE_BIN: "/assets/android/recycle-bin.svg",
  FOLDER: "/assets/android/folder.svg",
  FILE: "/assets/android/file.svg",
  MEMO: "/assets/android/memo.svg",
  CHECKLIST: "/assets/android/checklist.svg",
  STORAGE_STATUS: "/assets/android/storage-status.svg",
} as const;

export const MOBILE_WIDGET_ICON_PATH = {
  [WIDGET_TYPE.MEMO]: MOBILE_ASSET_PATHS.MEMO,
  [WIDGET_TYPE.DAILY_CHECKLIST]: MOBILE_ASSET_PATHS.CHECKLIST,
  [WIDGET_TYPE.STORAGE_STATUS]: MOBILE_ASSET_PATHS.STORAGE_STATUS,
} as const satisfies Partial<Record<
  (typeof WIDGET_TYPE)[keyof typeof WIDGET_TYPE],
  string
>>;

export const MOBILE_ACTIVITY_KIND = {
  HOME: "home",
  DIRECTORY: "directory",
  COMPUTER: "computer",
  TRASH: "trash",
  MEDIA: "media",
  WIDGET_FILE: "widget-file",
  WIDGET_DRAFT: "widget-draft",
  STORAGE_STATUS: "storage-status",
  WALLPAPER: "wallpaper",
} as const;

export const MOBILE_ACTIVITY_MENU_AVAILABILITY = {
  [MOBILE_ACTIVITY_KIND.HOME]: true,
  [MOBILE_ACTIVITY_KIND.DIRECTORY]: true,
  [MOBILE_ACTIVITY_KIND.COMPUTER]: false,
  [MOBILE_ACTIVITY_KIND.TRASH]: true,
  [MOBILE_ACTIVITY_KIND.MEDIA]: true,
  [MOBILE_ACTIVITY_KIND.WIDGET_FILE]: false,
  [MOBILE_ACTIVITY_KIND.WIDGET_DRAFT]: true,
  [MOBILE_ACTIVITY_KIND.STORAGE_STATUS]: false,
  [MOBILE_ACTIVITY_KIND.WALLPAPER]: false,
} as const;

export const MOBILE_SYSTEM_ITEM_ID = {
  DOCUMENTS: "mobile-system-documents",
  COMPUTER: "mobile-system-computer",
  RECYCLE_BIN: "mobile-system-recycle-bin",
} as const;

export const MOBILE_COPY = {
  APP_NAME: "Computer Room",
  LOADING: "연결하는 중…",
  LOAD_FAILED: "페이지를 불러오지 못했습니다.",
  RETRY: "다시 시도",
  BACK: "뒤로",
  HOME: "홈",
  MENU: "메뉴",
  CLOSE_MENU: "메뉴 닫기",
  MY_DOCUMENTS: "내 문서",
  MY_COMPUTER: "내 컴퓨터",
  RECYCLE_BIN: "휴지통",
  REFRESH: "새로 고침",
  DETAILS: "상세 정보",
  SORT: "정렬",
  SORT_TITLE: (name: string) => `${name} 정렬`,
  APPLY: "적용",
  LOGOUT: "로그아웃",
  HOME_SCREEN: "홈 화면",
  HOME_PAGES: "홈 화면 페이지",
  NAVIGATION_LABEL: "Android 탐색",
  CURRENT_PATH: "현재 경로",
  DIRECTORY_KIND: "폴더",
  WIDGET_KIND: "위젯",
  EMPTY_DIRECTORY: "이 폴더는 비어 있습니다.",
  EMPTY_TRASH: "휴지통이 비어 있습니다.",
  LOAD_MORE: "더 보기",
  DOWNLOAD: "다운로드",
  DOWNLOAD_CONFIRM: (name: string) => `${name} 파일을 다운로드할까요?`,
  CANCEL: "취소",
  CONFIRM: "확인",
  FILE_SIZE: "크기",
  ORIGINAL_LOCATION: "원래 위치",
  DELETED_AT: "삭제한 날짜",
  WIDGET_CATALOG_DESCRIPTION: "사용할 기능을 선택하세요.",
  CREATE_MEMO: "새 메모",
  CREATE_CHECKLIST: "새 일일 체크리스트",
  OPEN_STORAGE_STATUS: "저장소 상태",
  DRAFT_EXISTS_TITLE: "작성 중인 위젯",
  DRAFT_EXISTS_MESSAGE: "먼저 작성 중인 위젯을 이어서 쓰거나 삭제해 주세요.",
  RESUME_DRAFT: "이어쓰기",
  DELETE_DRAFT: "초안 삭제",
  DELETE_DRAFT_CONFIRM: "작성 중인 초안을 삭제할까요?",
  SAVE_LOCAL: "저장",
  SAVE_AS_FILE: "파일로 저장",
  LOCAL_SAVED: "이 기기에 저장했습니다.",
  DISCARD_CHANGES: "변경 취소",
  KEEP_EDITING: "계속 편집",
  UNSAVED_CHANGES: "저장하지 않은 변경 사항이 있습니다.",
  DRAFT_STORAGE_FAILED: "이 기기에 초안을 저장할 수 없습니다.",
  DRAFT_CORRUPTED: "손상된 로컬 초안을 삭제했습니다.",
  FILE_SAVE_TITLE: "위젯 파일로 저장",
  FILE_NAME: "파일 이름",
  SAVE_LOCATION: "저장 위치",
  SAVE_HERE: "여기에 저장",
  SAVING: "저장 중…",
  SAVE_FAILED: "위젯 파일을 저장하지 못했습니다.",
  NO_SUBDIRECTORIES: "하위 폴더가 없습니다.",
  EDIT: "편집",
  DONE: "완료",
  ADD_ITEM: "항목 추가",
  NEW_ITEM_PLACEHOLDER: "새 체크 항목",
  EDIT_ITEM: "수정",
  DELETE_ITEM: "삭제",
  HISTORY: "로그",
  NO_LOGS: "기록이 없습니다.",
  STATUS_DRAFT_RETAINED: "로그아웃해도 이 기기의 작성 중 초안은 유지됩니다.",
  WALLPAPER: "배경화면",
  WALLPAPER_PREVIEW: "배경화면 미리보기",
  DEFAULT_WALLPAPER: "기본 Android 배경",
  USE_DEFAULT_WALLPAPER: "기본 배경 사용",
  SET_WALLPAPER: "배경화면 설정",
  NO_WALLPAPER_IMAGES: "이 폴더에는 선택할 수 있는 이미지가 없습니다.",
  WALLPAPER_LOAD_FAILED: "배경화면 설정을 불러오지 못했습니다.",
  WALLPAPER_SAVE_FAILED: "배경화면 설정을 저장하지 못했습니다.",
  WALLPAPER_PREVIEW_FAILED: "이 이미지를 배경화면으로 표시할 수 없습니다.",
  SORT_SAVE_FAILED: "정렬 설정을 저장하지 못했습니다.",
} as const;

export const MOBILE_NAVIGATION_GLYPH = {
  BACK: "↩",
  HOME: "⌂",
  MENU: "▤",
} as const;

export const MOBILE_CLASS_NAME = {
  ROOT: "android-mobile",
  SCREEN: "android-mobile__screen",
  ACTIVITY: "android-activity",
  ACTIVITY_HEADER: "android-activity__header",
  ACTIVITY_TITLE: "android-activity__title",
  ACTIVITY_CONTENT: "android-activity__content",
  NAVIGATION: "android-navigation",
  NAVIGATION_BUTTON: "android-navigation__button",
  MENU: "android-menu",
  MENU_BACKDROP: "android-menu__backdrop",
  MENU_PANEL: "android-menu__panel",
  HOME: "android-home",
  HOME_PAGES: "android-home__pages",
  HOME_PAGE: "android-home__page",
  HOME_INDICATOR: "android-home__indicator",
  HOME_DOT: "android-home__dot",
  ICON: "android-icon",
  ICON_IMAGE: "android-icon__image",
  ICON_LABEL: "android-icon__label",
  LIST: "android-list",
  LIST_ITEM: "android-list__item",
  LIST_ICON: "android-list__icon",
  LIST_TEXT: "android-list__text",
  LIST_META: "android-list__meta",
  BREADCRUMBS: "android-breadcrumbs",
  MESSAGE: "android-message",
  ERROR: "android-message android-message--error",
  BUTTON_ROW: "android-button-row",
  DIALOG_BACKDROP: "android-dialog__backdrop",
  DIALOG: "android-dialog",
  FORM: "android-form",
  FIELD: "android-form__field",
  WIDGET: "android-widget",
  TOOLBAR: "android-widget__toolbar",
  WIDGET_CHECKLIST: "android-widget__checklist",
  WIDGET_PANEL: "android-widget__panel",
  MEDIA: "android-media",
  MEDIA_VIEWPORT: "android-media__viewport",
  MEDIA_NAVIGATION_ERROR: "android-media__navigation-error",
  MEDIA_ACTIONS: "android-media__actions",
  FOLDER_DETAILS: "android-folder-details",
  FOLDER_DETAILS_ROW: "android-folder-details__row",
  FOLDER_SORT: "android-folder-sort",
  WALLPAPER: "android-wallpaper",
  WALLPAPER_ROOTS: "android-wallpaper__roots",
  WALLPAPER_PREVIEW: "android-wallpaper__preview",
  WALLPAPER_PREVIEW_IMAGE: "android-wallpaper__preview-image",
  WALLPAPER_PREVIEW_DEFAULT: "android-wallpaper__preview-default",
  WALLPAPER_DEFAULT: "android-wallpaper__default",
  WALLPAPER_SELECTED: "android-wallpaper__selected",
  WALLPAPER_ERROR: "android-wallpaper__error",
  WALLPAPER_ACTIONS: "android-wallpaper__actions",
} as const;
