export const FILESYSTEM_COPY = {
  DESKTOP_SHORTCUTS: "바탕 화면 바로가기",
  FILE_TOOLBAR: "파일 및 폴더 작업",
  RECYCLE_BIN_TOOLBAR: "휴지통 작업",
  WIDGET_TOOLBAR: "위젯 작업",
  OPEN: "열기",
  BACK: "뒤로",
  UP: "위로",
  NEW_FOLDER: "새 폴더",
  UPLOAD: "업로드",
  DOWNLOAD: "다운로드",
  RENAME: "이름 변경",
  MOVE: "이동",
  DELETE: "삭제",
  ADDRESS: "주소",
  NAME: "이름",
  TYPE: "종류",
  SIZE: "크기",
  DELETED_AT: "삭제한 날짜",
  ORIGINAL_LOCATION: "원래 위치",
  EMPTY_DIRECTORY: "이 폴더는 비어 있습니다.",
  EMPTY_TRASH: "휴지통이 비어 있습니다.",
  LOAD_FAILED: "파일 목록을 불러오지 못했습니다.",
  CHANGE_FAILED: "파일 작업을 완료하지 못했습니다.",
  LOAD_MORE: "더 보기",
  SELECTED: "1개 항목 선택됨",
  ITEM_COUNT_SUFFIX: "개 항목",
  FOLDER: "파일 폴더",
  FILE: "파일",
  CREATE_FOLDER_TITLE: "새 폴더 만들기",
  RENAME_TITLE: "이름 변경",
  MOVE_TITLE: "항목 이동",
  FOLDER_NAME: "폴더 이름",
  ENTRY_NAME: "새 이름",
  MOVE_HERE: "여기로 이동",
  CANCEL: "취소",
  CONFIRM: "확인",
  RESTORE: "복원",
  PERMANENT_DELETE: "영구 삭제",
  EMPTY_RECYCLE_BIN: "휴지통 비우기",
  PERMANENT_DELETE_CONFIRM: "선택한 항목을 영구적으로 삭제할까요? 이 작업은 되돌릴 수 없습니다.",
  EMPTY_RECYCLE_BIN_CONFIRM: "휴지통의 모든 항목을 영구적으로 삭제할까요?",
  MY_COMPUTER_DESCRIPTION: "사용할 위젯을 선택하면 바탕 화면에 새 창이 생성됩니다.",
  RUN_WIDGET: "위젯 실행",
  BUSY: "처리 중…",
  BYTE_UNIT: "B",
  KILOBYTE_UNIT: "KB",
  MEGABYTE_UNIT: "MB",
} as const;

export const FILE_SIZE_DISPLAY = {
  KILOBYTE_BYTES: 1_000,
  MEGABYTE_BYTES: 1_000_000,
  FRACTION_DIGITS: 1,
} as const;
