export const FILESYSTEM_COPY = {
  DESKTOP_SHORTCUTS: "바탕 화면 바로가기",
  FILE_TOOLBAR: "파일 및 폴더 작업",
  RECYCLE_BIN_TOOLBAR: "휴지통 작업",
  WIDGET_TOOLBAR: "프로그램 작업",
  OPEN: "열기",
  RETRY: "다시 시도",
  REFRESH: "새로 고침",
  BACK: "뒤로",
  UP: "위로",
  NEW_FOLDER: "새 폴더",
  UPLOAD: "업로드",
  UPLOAD_FILES: "파일 업로드",
  UPLOAD_FOLDER: "폴더 업로드",
  DOWNLOAD: "다운로드",
  RENAME: "이름 변경",
  MOVE: "이동",
  DELETE: "삭제",
  ADDRESS: "주소",
  NAME: "이름",
  TYPE: "종류",
  SIZE: "크기",
  DELETED_AT: "삭제한 날짜",
  ORIGINAL_LOCATION: "원래 위치",
  EMPTY_DIRECTORY: "이 폴더는 비어 있습니다.",
  EMPTY_TRASH: "휴지통이 비어 있습니다.",
  LOAD_FAILED: "파일 목록을 불러오지 못했습니다.",
  CHANGE_FAILED: "파일 작업을 완료하지 못했습니다.",
  LOAD_MORE: "더 보기",
  SELECTED: "1개 항목 선택됨",
  SELECTED_COUNT: (count: number) => `${count}개 항목 선택됨`,
  ITEM_COUNT_SUFFIX: "개 항목",
  FOLDER: "파일 폴더",
  FILE: "파일",
  CREATE_FOLDER_TITLE: "새 폴더 만들기",
  RENAME_TITLE: "이름 변경",
  MOVE_TITLE: "항목 이동",
  FOLDER_NAME: "폴더 이름",
  ENTRY_NAME: "새 이름",
  MOVE_HERE: "여기로 이동",
  CANCEL: "취소",
  CONFIRM: "확인",
  RESTORE: "복원",
  PERMANENT_DELETE: "영구 삭제",
  EMPTY_RECYCLE_BIN: "휴지통 비우기",
  PERMANENT_DELETE_CONFIRM:
    "선택한 항목을 영구적으로 삭제할까요? 이 작업은 되돌릴 수 없습니다.",
  EMPTY_RECYCLE_BIN_CONFIRM: "휴지통의 모든 항목을 영구적으로 삭제할까요?",
  MY_COMPUTER_DESCRIPTION:
    "사용할 프로그램을 선택하면 바탕 화면에 새 창이 생성됩니다.",
  RUN_APPLICATION: "프로그램 실행",
  BUSY: "처리 중…",
  DELETION_INCOMPLETE: "삭제 미완료 · 복원 불가",
  TRANSFER_STOP: "중단",
  TRANSFER_STOPPING: "진행 중인 요청이 끝나면 중단합니다.",
  TRANSFER_RETRY: "남은 항목 다시 시도",
  TRANSFER_PENDING_NOTICE: "미완료 전송이 있습니다. 남은 항목을 다시 시도하거나 결과 창을 닫아 주세요.",
  TRANSFER_RETRY_NOTICE: "서버 저장 후 응답이 유실된 파일은 재시도하면 중복으로 추가될 수 있습니다.",
  TRANSFER_CLOSE_NOTICE: "닫으면 남은 항목의 재시도 목록이 사라집니다.",
  TRANSFER_COUNTS: (total: number, succeeded: number, failed: number, remaining: number) =>
    `전체 ${total} · 성공 ${succeeded} · 실패 ${failed} · 남은 항목 ${remaining}`,
  TRANSFER_TITLE: "파일 전송",
  TRANSFER_PROGRESS: "항목을 전송하는 중입니다.",
  TRANSFER_COMPLETE: "파일 전송이 완료되었습니다.",
  TRANSFER_PARTIAL: "일부 항목을 전송하지 못했습니다.",
  TRANSFER_FAILED: "파일 전송에 실패했습니다.",
  TRANSFER_FAILURE_ITEM: "실패",
  TRANSFER_SKIPPED_ITEM: "건너뜀",
  FOLDER_DROP_UNSUPPORTED:
    "이 브라우저에서는 폴더 드롭을 지원하지 않아 파일만 업로드했습니다.",
  DROP_NOT_ALLOWED: "이 위치에는 항목을 놓을 수 없습니다.",
  DESKTOP_OVERFLOW: (count: number) =>
    `현재 화면에 표시하지 못한 바탕 화면 항목이 ${count}개 있습니다.`,
  OPEN_DESKTOP: "바탕 화면 열기",
  CLOSE: "닫기",
  BATCH_RESULT_TITLE: "파일 작업 결과",
  BATCH_PARTIAL: "일부 항목을 처리하지 못했습니다.",
  BATCH_SUCCESS_COUNT: (count: number) => `${count}개 항목 처리 완료`,
  DOWNLOAD_TITLE: "파일 다운로드",
  DOWNLOAD_PREPARING: "다운로드할 항목을 확인하는 중입니다.",
  DOWNLOAD_PROGRESS: (completed: number, total: number) =>
    `${total}개 중 ${completed}개 파일을 저장하는 중입니다.`,
  DOWNLOAD_BYTE_PROGRESS: (transferred: string, total: string) =>
    `${transferred} / ${total}`,
  DOWNLOAD_UNSUPPORTED:
    "이 브라우저는 디스크 스트리밍 다운로드를 지원하지 않습니다. 최신 Edge 또는 Chrome을 사용해 주세요.",
  DOWNLOAD_EMPTY: "다운로드할 일반 파일이나 폴더가 없습니다.",
  DOWNLOAD_FAILED:
    "ZIP 파일을 저장하지 못했습니다. 다운로드를 다시 시도해 주세요.",
  DOWNLOAD_FILE_FAILED: (path: string) =>
    `${path} 파일을 가져오지 못했습니다. 다운로드를 다시 시도해 주세요.`,
  DOWNLOAD_CANCEL: "다운로드 취소",
  DOWNLOAD_SKIPPED_WIDGETS: (count: number) =>
    `프로그램 문서 ${count}개는 ZIP에서 제외했습니다.`,
  CONTEXT_MENU: "바탕 화면 항목 메뉴",
  WIDGET: "프로그램 문서",
  SAVE_WIDGET_TITLE: "프로그램 문서로 저장",
  SAVE_LOCATION: "저장 위치",
  FILE_NAME: "파일 이름",
  SAVE_HERE: "저장",
  UNSAVED_CLOSE_TITLE: "저장하지 않은 프로그램",
  UNSAVED_CLOSE_MESSAGE: "이 프로그램을 문서로 저장하시겠습니까?",
  SAVE: "저장",
  DONT_SAVE: "저장 안 함",
  BYTE_UNIT: "B",
  KILOBYTE_UNIT: "KB",
  MEGABYTE_UNIT: "MB",
  GIGABYTE_UNIT: "GB",
  TERABYTE_UNIT: "TB",
} as const;
