import type { SearchDirectory } from "@client/types/filesystem/search/search";
import type { useFilesystemUpload } from "@client/hooks/filesystem/use-filesystem-upload";
import type { MobileNavigationGuard } from "@client/hooks/mobile/filesystem/use-mobile-file-actions";
import type { FilesystemSearchQuery } from "@/types/filesystem/search/search";
import type { FilesystemEntry, FilesystemFileEntry } from "@/types/filesystem/filesystem";
import type { MobilePreferences } from "@/types/platform/mobile-preferences";
import type { WidgetFileDocument, WidgetFileType } from "@/types/widgets/widget-file";
import type { MobileActivity } from "@client/types/app/mobile-navigation";
import type { LocalWidgetDraft } from "@client/types/widgets/local-widget-draft";

export interface MobileShellController {
  readonly transfer: ReturnType<typeof useFilesystemUpload>;
  filesChanged(): void;
  uploadFiles(files: FileList, directoryId: string): void;
  setFileNavigationGuard(guard: MobileNavigationGuard): void;
  readonly currentActivity: MobileActivity;
  readonly canGoBack: boolean;
  readonly menuEnabled: boolean;
  readonly menuOpen: boolean;
  readonly revision: number;
  readonly desktopEntries: readonly FilesystemEntry[];
  readonly desktopError: string | null;
  readonly draft: LocalWidgetDraft | null;
  readonly draftError: string | null;
  readonly preferences: MobilePreferences;
  readonly preferencesLoading: boolean;
  readonly preferencesSaving: boolean;
  readonly preferencesError: string | null;
  readonly pendingDownload: FilesystemFileEntry | null;
  readonly draftConflictOpen: boolean;
  openSearch(directory: SearchDirectory): void;
  rememberSearch(query: FilesystemSearchQuery): void;
  refresh(): void;
  closeMenu(): void;
  toggleMenu(): void;
  goBack(): void;
  goHome(): void;
  openDirectory(directoryId: string, title: string): void;
  openComputer(): void;
  openTrash(): void;
  openWallpaper(): void;
  openStorageStatus(): void;
  replaceWithStorageStatus(): void;
  openEntry(entry: FilesystemEntry): void;
  changeMediaFile(file: FilesystemFileEntry): void;
  downloadCurrentMedia(): void;
  createDraft(type: WidgetFileType): void;
  saveDraft(draft: LocalWidgetDraft): boolean;
  completeDraftFile(document: WidgetFileDocument): void;
  discardCurrentDraft(): void;
  resumeDraftConflict(): void;
  discardConflictingDraft(): void;
  dismissDraftConflict(): void;
  clearDraftError(): void;
  setDirty(dirty: boolean): void;
  confirmPendingDownload(): void;
  cancelPendingDownload(): void;
  updateWallpaper(entryId: string | null): Promise<boolean>;
  refreshPreferences(): Promise<void>;
}
