export const IMAGE_UPLOAD_LOG_OUTCOME = {
  SUCCESS: "success",
  FAILURE: "failure",
} as const;

export const IMAGE_UPLOAD_LOG_OUTCOME_VALUES = [
  IMAGE_UPLOAD_LOG_OUTCOME.SUCCESS,
  IMAGE_UPLOAD_LOG_OUTCOME.FAILURE,
] as const;

export const IMAGE_UPLOAD_LOG_SETTINGS_SINGLETON_ID = 1;

export const IMAGE_UPLOAD_LOG_RETENTION = {
  DEFAULT_DAYS: 30,
  MIN_DAYS: 1,
  MAX_DAYS: 365,
} as const;

export const IMAGE_UPLOAD_LOG_PAGE_LIMIT = 100;

export const IMAGE_UPLOAD_LOG_CURSOR_SEPARATOR = ".";
export const IMAGE_UPLOAD_LOG_CURSOR_ID_PATTERN = /^[a-zA-Z0-9-]+$/u;

export const IMAGE_UPLOAD_LOG_LIMITS = {
  CONTENT_TYPE_MAX_LENGTH: 255,
  ERROR_CODE_MAX_LENGTH: 128,
  ERROR_MESSAGE_MAX_LENGTH: 500,
  SOURCE_IP_MAX_LENGTH: 45,
} as const;
