import { KOREA_TIME_ZONE } from "@/constants/platform/date";
import { UI_LOCALE } from "@client/content/ko/shared/format";

export const IMAGE_UPLOAD_LOG_COPY = {
  TABS_LABEL: "이미지 API 프로필 화면",
  PROFILES_TAB: "프로필",
  LOGS_TAB: "수신 기록",
  FILTER_PROFILE: "프로필",
  FILTER_RESULT: "결과",
  ALL_PROFILES: "모든 프로필",
  ALL_RESULTS: "모든 결과",
  SUCCESS: "성공",
  FAILURE: "실패",
  RECEIVED_AT: "수신 시각",
  FILE_OR_ERROR: "파일 또는 오류",
  CONTENT_TYPE: "형식",
  SIZE: "크기",
  DURATION: "처리 시간",
  SOURCE_IP: "송신 IP",
  UNKNOWN_PROFILE: "알 수 없는 프로필",
  EMPTY_VALUE: "-",
  UNAVAILABLE_FILE: "파일이 이동되었거나 휴지통에 있습니다.",
  EMPTY: "조건에 맞는 수신 기록이 없습니다.",
  LOADING: "수신 기록을 불러오는 중…",
  LOAD_FAILED: "이미지 수신 기록을 불러오지 못했습니다.",
  RETRY: "다시 시도",
  LOAD_MORE: "더 보기",
  SETTINGS_GROUP: "보관 정책",
  RETENTION_DAYS: "보관 기간(일)",
  RETENTION_RANGE: "1~365일 사이의 정수를 입력하세요.",
  SAVE_SETTINGS: "설정 저장",
  SETTINGS_LOADING: "보관 설정을 불러오는 중…",
  SETTINGS_LOAD_FAILED: "이미지 수신 기록 설정을 불러오지 못했습니다.",
  SETTINGS_SAVE_FAILED: "이미지 수신 기록 설정을 저장하지 못했습니다.",
  INVALID_RETENTION_DAYS: "보관 기간은 1~365일 사이의 정수여야 합니다.",
  RETENTION_NOTICE: (retentionDays: number) =>
    `기록은 ${retentionDays}일간 표시되며 지난 기록은 매일 00:00 KST에 정리합니다.`,
  MILLISECONDS: (value: number) => `${value} ms`,
  HTTP_STATUS: (value: number) => `HTTP ${value}`,
} as const;

export const IMAGE_UPLOAD_LOG_DATE_FORMAT = new Intl.DateTimeFormat(UI_LOCALE, {
  timeZone: KOREA_TIME_ZONE,
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
  hour: "2-digit",
  minute: "2-digit",
  second: "2-digit",
  hour12: false,
});
