import { FILESYSTEM_ENTRY_KIND } from "@/constants/filesystem/filesystem";
export const FILESYSTEM_SEARCH_MODE = {
  NAME: "name",
  CONTENT: "content",
  ALL: "all",
} as const;
export const SEARCH_EXCERPT_CONTEXT = 40;
export const SEARCH_EXCERPT_LENGTH = 320;
export const FILESYSTEM_SEARCH_KIND = {
  ALL: "all",
  SHORTCUT: FILESYSTEM_ENTRY_KIND.SHORTCUT,
  FILE: FILESYSTEM_ENTRY_KIND.FILE,
  DIRECTORY: FILESYSTEM_ENTRY_KIND.DIRECTORY,
  PROGRAM: FILESYSTEM_ENTRY_KIND.WIDGET,
} as const;
