export const FILESYSTEM_SORT_FIELD = {
  NAME: "name",
  CREATED_AT: "createdAt",
  UPDATED_AT: "updatedAt",
  TYPE: "type",
  SIZE: "size",
} as const;

export const FILESYSTEM_SORT_FIELD_VALUES = [
  FILESYSTEM_SORT_FIELD.NAME,
  FILESYSTEM_SORT_FIELD.CREATED_AT,
  FILESYSTEM_SORT_FIELD.UPDATED_AT,
  FILESYSTEM_SORT_FIELD.TYPE,
  FILESYSTEM_SORT_FIELD.SIZE,
] as const;

export const FILESYSTEM_SORT_DIRECTION = {
  ASCENDING: "ascending",
  DESCENDING: "descending",
} as const;

export const FILESYSTEM_SORT_DIRECTION_VALUES = [
  FILESYSTEM_SORT_DIRECTION.ASCENDING,
  FILESYSTEM_SORT_DIRECTION.DESCENDING,
] as const;

export const DEFAULT_FILESYSTEM_DIRECTORY_SORT = {
  field: FILESYSTEM_SORT_FIELD.CREATED_AT,
  direction: FILESYSTEM_SORT_DIRECTION.DESCENDING,
} as const;
