export const XP_CONTEXT_MENU_COPY = {
  LABEL: "바로 가기 메뉴",
  OPEN: "열기",
  OPEN_NEW_WINDOW: "새 창에서 열기",
  COPY_ADDRESS: "주소 복사",
  CUT: "잘라내기",
  COPY: "복사",
  PASTE: "붙여넣기",
  DELETE: "삭제",
  SELECT_ALL: "전체 선택",
  REFRESH_PAGE: "페이지 새로고침",
  STORAGE_STATUS: "저장소 상태 열기",
  CLIPBOARD_FAILED: "클립보드 작업을 완료하지 못했습니다.",
  COMMAND_FAILED: "메뉴 명령을 완료하지 못했습니다.",
} as const;
