export const API_PATHS = {
  SESSION: "/api/session",
  FILES: "/api/files",
  FILESYSTEM: "/api/filesystem",
  INTEGRATIONS: "/api/integrations",
  WIDGETS: "/api/widgets",
  WIDGET_FILES: "/api/widget-files",
  STORAGE_STATUS: "/api/storage/status",
  PREFERENCES: "/api/preferences",
} as const;

export const API_PATH_SEGMENTS = {
  MEMO: "memo",
  CHECKLIST: "checklist",
  ITEMS: "items",
  CHECK: "check",
  LOGS: "logs",
  ENTRIES: "entries",
  DIRECTORIES: "directories",
  TRASH: "trash",
  RESTORE: "restore",
  CONTENT: "content",
  THUMBNAIL: "thumbnail",
  MOVE: "move",
  FILE: "file",
  OPEN: "open",
  CLOSE: "close",
  NOVELAI: "novelai",
  IMAGES: "images",
  BATCH: "batch",
  DOWNLOADS: "downloads",
  MANIFEST: "manifest",
  DELETE: "delete",
  SORT: "sort",
  DETAILS: "details",
  MOBILE: "mobile",
} as const;

export const FILESYSTEM_API_PATHS = {
  ENTRIES: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.ENTRIES}`,
  DIRECTORIES: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.DIRECTORIES}`,
  TRASH: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.TRASH}`,
  DOWNLOADS: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.DOWNLOADS}`,
  BATCH_MOVE:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.ENTRIES}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.MOVE}`,
  BATCH_TRASH:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.ENTRIES}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.TRASH}`,
  BATCH_RESTORE:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.TRASH}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.RESTORE}`,
  BATCH_DELETE:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.TRASH}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.DELETE}`,
  DOWNLOAD_MANIFEST:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.DOWNLOADS}/${API_PATH_SEGMENTS.MANIFEST}`,
} as const;

export const NOVELAI_IMAGE_UPLOAD_API_PATH =
  `${API_PATHS.INTEGRATIONS}/${API_PATH_SEGMENTS.NOVELAI}/${API_PATH_SEGMENTS.IMAGES}`;

export const MOBILE_PREFERENCES_API_PATH =
  `${API_PATHS.PREFERENCES}/${API_PATH_SEGMENTS.MOBILE}`;

export const API_QUERY_PARAMETERS = {
  OFFSET: "offset",
  LIMIT: "limit",
  FILE_NAME: "name",
  PARENT_ID: "parentId",
  DESKTOP_TARGET_INDEX: "desktopTargetIndex",
  DESKTOP_CAPACITY: "desktopCapacity",
} as const;
