export const API_PATHS = {
  ADMIN: "/api/admin",
  GUEST: "/api/guest",
  SESSION: "/api/session",
  FILESYSTEM: "/api/filesystem",
  INTEGRATIONS: "/api/integrations",
  WIDGETS: "/api/widgets",
  WIDGET_FILES: "/api/widget-files",
  STORAGE_STATUS: "/api/storage/status",
  PREFERENCES: "/api/preferences",
} as const;

export const API_PATH_SEGMENTS = {
  FILESYSTEM: "filesystem",
  MEMO: "memo",
  CHECKLIST: "checklist",
  ITEMS: "items",
  CHECK: "check",
  LOGS: "logs",
  ENTRIES: "entries",
  FILES: "files",
  DIRECTORIES: "directories",
  TRASH: "trash",
  RESTORE: "restore",
  CONTENT: "content",
  THUMBNAIL: "thumbnail",
  MOVE: "move",
  FILE: "file",
  OPEN: "open",
  CLOSE: "close",
  NOVELAI: "novelai",
  IMAGES: "images",
  BATCH: "batch",
  DOWNLOADS: "downloads",
  DOWNLOAD: "download",
  MANIFEST: "manifest",
  DELETE: "delete",
  SORT: "sort",
  DETAILS: "details",
  MOBILE: "mobile",
  IMAGE_PROFILES: "image-profiles",
  IMAGE_UPLOAD_LOGS: "image-upload-logs",
  GUEST_ACCESS: "guest-access",
  SESSION: "session",
  PROGRAM_DOCUMENTS: "program-documents",
} as const;

export const FILESYSTEM_API_PATHS = {
  ENTRIES: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.ENTRIES}`,
  FILES: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.FILES}`,
  DIRECTORIES: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.DIRECTORIES}`,
  TRASH: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.TRASH}`,
  DOWNLOADS: `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.DOWNLOADS}`,
  BATCH_MOVE:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.ENTRIES}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.MOVE}`,
  BATCH_TRASH:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.ENTRIES}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.TRASH}`,
  BATCH_RESTORE:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.TRASH}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.RESTORE}`,
  BATCH_DELETE:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.TRASH}/${API_PATH_SEGMENTS.BATCH}/${API_PATH_SEGMENTS.DELETE}`,
  DOWNLOAD_MANIFEST:
    `${API_PATHS.FILESYSTEM}/${API_PATH_SEGMENTS.DOWNLOADS}/${API_PATH_SEGMENTS.MANIFEST}`,
} as const;

export const NOVELAI_IMAGE_UPLOAD_API_PATH =
  `${API_PATHS.INTEGRATIONS}/${API_PATH_SEGMENTS.NOVELAI}/${API_PATH_SEGMENTS.IMAGES}`;

export const IMAGE_UPLOAD_PROFILES_API_PATH =
  `${API_PATHS.INTEGRATIONS}/${API_PATH_SEGMENTS.IMAGE_PROFILES}`;

export const IMAGE_UPLOAD_LOGS_API_PATH =
  `${API_PATHS.INTEGRATIONS}/${API_PATH_SEGMENTS.IMAGE_UPLOAD_LOGS}`;

export const GUEST_ACCESS_API_PATH =
  `${API_PATHS.ADMIN}/${API_PATH_SEGMENTS.GUEST_ACCESS}`;

export const GUEST_ACCESS_API_PATHS = {
  DIRECTORIES: `${GUEST_ACCESS_API_PATH}/${API_PATH_SEGMENTS.DIRECTORIES}`,
  ENTRIES: `${GUEST_ACCESS_API_PATH}/${API_PATH_SEGMENTS.ENTRIES}`,
} as const;

export const GUEST_API_PATHS = {
  SESSION: `${API_PATHS.GUEST}/${API_PATH_SEGMENTS.SESSION}`,
  DIRECTORIES: `${API_PATHS.GUEST}/${API_PATH_SEGMENTS.FILESYSTEM}/${API_PATH_SEGMENTS.DIRECTORIES}`,
  FILES: `${API_PATHS.GUEST}/${API_PATH_SEGMENTS.FILESYSTEM}/${API_PATH_SEGMENTS.FILES}`,
  PROGRAM_DOCUMENTS: `${API_PATHS.GUEST}/${API_PATH_SEGMENTS.PROGRAM_DOCUMENTS}`,
} as const;

export const MOBILE_PREFERENCES_API_PATH =
  `${API_PATHS.PREFERENCES}/${API_PATH_SEGMENTS.MOBILE}`;

export const API_QUERY_PARAMETERS = {
  OFFSET: "offset",
  LIMIT: "limit",
  FILE_NAME: "name",
  PARENT_ID: "parentId",
  DESKTOP_TARGET_INDEX: "desktopTargetIndex",
  DESKTOP_CAPACITY: "desktopCapacity",
  PROFILE_ID: "profileId",
  OUTCOME: "outcome",
  CURSOR: "cursor",
} as const;
