export const BACKGROUND_TASK_FAILURE_CODE = {
  THUMBNAIL_PREPARATION: "THUMBNAIL_PREPARATION_FAILED",
  IMAGE_UPLOAD_LOG_RECORDING: "IMAGE_UPLOAD_LOG_RECORDING_FAILED",
  IMAGE_UPLOAD_LOG_PURGE: "IMAGE_UPLOAD_LOG_PURGE_FAILED",
} as const;

export const BACKGROUND_TASK_LOG_EVENT = "background_task_failed";
